distributedSystems/java/Assignment3/Assignment3-war/src/java/lorenzo/pat/controllers/AdminController.java
package lorenzo.pat.controllers;

import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import lorenzo.pat.entities.Book;
import lorenzo.pat.services.BookServiceLocal;


@ManagedBean(name = "adminController")
@RequestScoped
public class AdminController {
  
  @EJB
  private BookServiceLocal bookService;
  
  Book book;

  public AdminController() {
    book = new Book();
  }

  public String redirectToAddBook() {
    return "addBook";
  }

  public List<Book> getAllBooks() {
    return bookService.getAllBooks();
  }
  
  public String addBook() {
    bookService.addBook(book);
    return "admin";
  }
  
  public String deleteBook(int bookId) {
    book = bookService.findBook(bookId);
    bookService.removeBook(book);
    return "admin";
  }
  
  public String prepareUpdate(Book updateBook) {
    book = updateBook;
    return "update";
  }
  
  public String updateBook() {
    bookService.updateBook(book);
    return "admin";
  }
  
  public Book getBook() {
    return book;
  }

  public void setBook(Book book) {
    this.book = book;
  }
  
}

distributedSystems/java/Assignment3/Assignment3-war/src/java/lorenzo/pat/controllers/LoginController.java
package lorenzo.pat.controllers;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import lorenzo.pat.entities.User;
import lorenzo.pat.services.UserServiceLocal;

@ManagedBean(name = "loginController")
@SessionScoped
public class LoginController {

  @EJB
  private UserServiceLocal loginService;

  private User user;

  public LoginController() {
    user = new User();
  }

  public String checkLogin() {
    if (!loginService.isValidLogin(user.getUsername(), user.getPassword())) 
      return "register";
    
    user = loginService.getLoggedUser(user.getUsername(), user.getPassword());

    HttpSession session = getSession();
    session.setAttribute("loginUser", user);

    return (loginService.isAdmin(user)) ? "admin" : "user";
  }

  private HttpSession getSession() {
    FacesContext context = FacesContext.getCurrentInstance();
    HttpSession session = (HttpSession) context.getExternalContext().getSession(true);
    return session;
  }

  public String redirectToRegister() {
    return "register";
  }

  public String redirectToIndex() {
    return "index";
  }

  public String redirectToAdmin() {
    return "admin";
  }

  public String registerUser() {
    loginService.registerUser(user);
    return "index";
  }

  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

}

distributedSystems/java/Assignment3/Assignment3-war/src/java/lorenzo/pat/controllers/UserController.java
package lorenzo.pat.controllers;

import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import lorenzo.pat.entities.Book;
import lorenzo.pat.entities.ShoppingCart;
import lorenzo.pat.entities.User;
import lorenzo.pat.services.BookServiceLocal;
import lorenzo.pat.services.UserServiceLocal;

@ManagedBean
@RequestScoped
public class UserController {
  @EJB
  private UserServiceLocal userService;
  @EJB
  private BookServiceLocal bookService;

  public UserController() {
  }

  public void addToCart(Book book) {
    userService.addBookToCart(book, getLoggedUser());
  }

  public boolean isOnStock(Book book) {
    return book.getStock() > 0;
  }

  public Book getBook(ShoppingCart sc) {
    List<ShoppingCart> itemsInCart = userService.getShoppingCart(getLoggedUser());
    
    for (ShoppingCart s : itemsInCart) {
      if (s.equals(sc)) {
        return bookService.findBook(s.getShoppingCartPK().getBookId());
      }
    }

    return null;
  }

  public void buyBooks() {
    userService.buyBooks(getLoggedUser());
  }

  public void removeFromCart(Book book) {
    userService.removeBookFromCart(book, getLoggedUser());
  }

  public boolean isMoneyEnough() {
    User user = getLoggedUser();
    return (user.getMoneyAmount() >= getTotalPrice());
  }
  
  public int getTotalPrice() {
    return userService.getTotalPaySum(getLoggedUser());
  }

  public List<Book> getAllBooks() {
    return bookService.getAllBooks();
  }

  public List<ShoppingCart> getShoppingCart() {
    return userService.getShoppingCart(getLoggedUser());
  }

  public String redirectToCheckout() {
    return "checkout";
  }

  public String redirectToUser() {
    return "user";
  }

  public String redirectToindex() {
    return "index";
  }
  
  private User getLoggedUser() {
    HttpSession session = getSession();
    User user = (User) session.getAttribute("loginUser");
    return user;
  }

  private HttpSession getSession() {
    FacesContext context = FacesContext.getCurrentInstance();
    HttpSession session = (HttpSession) context.getExternalContext().getSession(true);
    return session;
  }

}

distributedSystems/java/Assignment3/Assignment3-war/web/addBook.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
  <h:head>
    <title>Admin</title>
  </h:head>
  <h:body>
    
    <h:form>
      <h:outputLabel value="Title: "/>    <h:inputText value="#{adminController.book.title}"/>      <br/>
      <h:outputLabel value="Author: "/>   <h:inputText value="#{adminController.book.author}"/>   <br/>
      <h:outputLabel value="Price: "/>    <h:inputText value="#{adminController.book.price}"/>      <br/>
      <h:outputLabel value="Stock: "/>    <h:inputText value="#{adminController.book.stock}"/>      <br/>
      
      <h:commandButton value="Add book" action="#{adminController.addBook()}"/>
    </h:form>
    
    <h:form>
      <h:commandLink value="Back" action="#{loginController.redirectToAdmin()}"/>
    </h:form>
    
  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
  <h:head>
    <title>Admin</title>
  </h:head>
  <h:body>
    
    <h:outputLabel value="Hello #{loginUser.username}!"/>
    
    <h:form>
      <h:commandLink value="Add package" action="#{adminController.redirectToAddPackage}"/>
    </h:form>
    
    <table>
      <thead>
        <tr>
          <th>Book id</th>
          <th>Title</th>
          <th>Author</th>
          <th>Price</th>
          <th>Stock</th>
          <th colspan="3">Action</th>
        </tr>
      </thead>

      <tbody>

        <c:forEach items="#{adminController.allBooks}" var="book">
          <tr>
            
            <h:form>
              <td><h:outputLabel value="#{book.id}" /></td>
              <td><h:outputLabel value="#{book.title}" /></td>
              <td><h:outputLabel value="#{book.author}" /></td>
              <td><h:outputLabel value="#{book.price}" /></td>
              <td><h:outputLabel value="#{book.stock}" /></td>
              <td>
                <h:commandButton value="Update" action="#{adminController.prepareUpdate(book)}"/>
              </td>
              <td>
                <h:commandButton value="Delete" action="#{adminController.deleteBook(book.id)}"/>
              </td>
              <td>
                <h:commandButton value="Delete" action="#{adminController.deleteBook(book.id)}"/>
              </td>
            </h:form>
       
          </tr>
        </c:forEach>
      </tbody>
    </table>
    
    <br/>
    <h:form>
      <h:commandLink value="Log out" action="#{loginController.redirectToIndex()}"/>
    </h:form>
  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/checkout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
  <h:head>
    <title>Book Store</title>
  </h:head>
  <h:body>

    <h:form>
      <h:outputLabel value="Hello #{loginUser.username}!"/>
      <h:commandLink value="Log out" action="#{userController.redirectToindex()}"/>
    </h:form>
    
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Price</th>
          <th>Items in cart</th>
          <th></th>
        </tr>
      </thead>

      <tbody>

        <c:forEach items="#{userController.shoppingCart}" var="sc">
          <tr>

            <h:form>
              <td><h:outputLabel value="#{userController.getBook(sc).title}" /></td>
              <td><h:outputLabel value="#{userController.getBook(sc).author}" /></td>
              <td><h:outputLabel value="#{userController.getBook(sc).price}" /></td>
              <td><h:outputLabel value="#{sc.items}" /></td>
              <td>
                <h:commandButton value="Remove from cart" action="#{userController.removeFromCart(userController.getBook(sc))}"/>
              </td>

            </h:form>

          </tr>
        </c:forEach>
      </tbody>
    </table>
    
    <h:outputText value="Total price: #{userController.totalPrice}. "/>
    <h:outputText value="Your balance: #{loginUser.moneyAmount}"/>
    
    <h:form>  
      <h:commandButton value="Buy books" action="#{userController.buyBooks()}" disabled="#{!userController.moneyEnough}"/>
      <h:outputText value="Not enough money" rendered="#{!userController.moneyEnough}"/>
    </h:form>
    
    <h:form>  
      <h:commandLink value="Back to shop" action="#{userController.redirectToUser()}"/>
    </h:form>

  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
  <h:head>
    <title>Book Shop</title>
  </h:head>
  <h:body>
    <h:outputText value="another dummy error page o_O"/>
    <h:commandButton value="Back to login page" action="#{loginController.redirectToIndex()}"/>
  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
  <h:head>
    <title>Book Store</title>
  </h:head>
  <h:body>
    <h:form>
      <h:outputLabel value="Wellcome!" /><br/>
      <h:outputLabel value="Username: " /> <h:inputText value="#{loginController.user.username}" /><br/>
      <h:outputLabel value="Password: " /> <h:inputSecret value="#{loginController.user.password}" /><br/>

      <h:commandButton action="#{loginController.checkLogin()}" value="Log in"/>
    </h:form>
    <h:form>
      <h:commandLink action="#{loginController.redirectToRegister()}" value="Register"/>
    </h:form>
  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
  <h:head>
    <title>Register</title>
  </h:head>
  <h:body>
    <h:outputText value="Wellcome! Please register"/>
    
    <h:form>
      
      <h:outputLabel value ="Username: "/>      <h:inputText value="#{loginController.user.username}"/>     <br/>
      <h:outputLabel value ="Password: "/>      <h:inputText value="#{loginController.user.password}"/>     <br/>
      <h:outputLabel value ="Mail: "/>          <h:inputText value="#{loginController.user.mail}"/>         <br/>
      <h:outputLabel value ="Money amount: "/>  <h:inputText value="#{loginController.user.moneyAmount}"/>  <br/>
      
      <h:commandButton action="#{loginController.registerUser()}" value="Register"/>

    </h:form>
    
    <h:form>
      <h:commandLink value="Back to login page" action="#{loginController.redirectToIndex()}"/>
    </h:form>
  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/update.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
  <h:head>
    <title>Admin</title>
  </h:head>
  <h:body>

    <h:form>
      <h:outputLabel value="Book id: "/>  <h:inputText value="#{adminController.book.id}" 
                                                      readonly="#{facesContext.renderResponse}"/>   <br/>
      <h:outputLabel value="Title: "/>    <h:inputText value="#{adminController.book.title}"/>      <br/>
      <h:outputLabel value="Author: "/>   <h:inputText value="#{adminController.book.author}"/>     <br/>
      <h:outputLabel value="Price: "/>    <h:inputText value="#{adminController.book.price}"/>      <br/>
      <h:outputLabel value="Stock: "/>    <h:inputText value="#{adminController.book.stock}"/>      <br/>
      <h:commandButton value="Update book" action="#{adminController.updateBook()}"/>
    </h:form>

  </h:body>
</html>

distributedSystems/java/Assignment3/Assignment3-war/web/user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
  <h:head>
    <title>Book Store</title>
  </h:head>
  <h:body>
    
    <h:form>
      <h:outputLabel value="Hello #{loginUser.username}!"/>
      <h:commandLink value="Log out" action="#{userController.redirectToindex()}"/>
    </h:form>
    
    <table>
      <thead>
        <tr>
          <th>Book id</th>
          <th>Title</th>
          <th>Author</th>
          <th>Price</th>
          <th>Stock</th>
          <th/>
          <th/>
        </tr>
      </thead>

      <tbody>

        <c:forEach items="#{userController.allBooks}" var="book">
          <tr>
            
            <h:form>
              <td><h:outputLabel value="#{book.id}" /></td>
              <td><h:outputLabel value="#{book.title}" /></td>
              <td><h:outputLabel value="#{book.author}" /></td>
              <td><h:outputLabel value="#{book.price}" /></td>
              <td><h:outputLabel value="#{book.stock}" /></td>
              <td>
                <h:commandButton value="add to cart" action="#{userController.addToCart(book)}" disabled="#{!userController.isOnStock(book)}"/>
              </td>
              <td><h:outputText value="Not on stock" rendered="#{!userController.isOnStock(book)}"/></td>
             
            </h:form>
       
          </tr>
        </c:forEach>
      </tbody>
    </table>
    
    <h:form>
      <h:commandLink value="Checkout" action="#{userController.redirectToCheckout()}"/> <br/>
    </h:form>
    
  </h:body>
</html>