distributedSystems/java/Assignment 5/Assignment5_Client/src/java/lorenzo/pat/controller/AdminController.java
package lorenzo.pat.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import lorenzo.pat.model.PackageService;
import lorenzo.pat.model.UserService;
import lorenzo.pat.webservice.City;
import lorenzo.pat.webservice.User;
import org.tempuri.Package;
import org.tempuri1.PackageHistory;

@ManagedBean(name = "adminController")
@SessionScoped
public class AdminController {

  private UserService userService;
  private PackageService packageService;
  private Package pack;
  private List<PackageHistory> packageHistory;

  public AdminController() {
    userService = new UserService();
    pack = new Package();
    packageService = new PackageService();
    packageHistory = new ArrayList<>();
  }

  public String addPackage() {
    packageService.addPackage(pack);
    return "sysUser";
  }

  public void removePackage(int packageId) {
    packageService.removePackage(packageId);
  }

  public List<Package> getAllPackages() {
    return packageService.getAllPackages();
  }

  public String prepareUpdate(Package updatePackage) {
    packageHistory = packageService.getHistoryForPackage(updatePackage.getPackageId());
    pack = updatePackage;
    return "update";
  }

  public void registerForTracking(int packageId) {
    packageService.registerPackageForTracking(packageId);
  }

  public void updatePackageStatus(String status) {
    System.out.println("new status = " + status + " " + pack.getPackageId());
    packageService.updatePackageStatus(pack.getPackageId(), status);
  }

  public List<City> getAllCities() {
    return userService.getAllCities();
  }

  public String getCityName(int cityId) {
    return userService.getCity(cityId).getName();

  }

  public void addToHistory(int cityId) throws DatatypeConfigurationException {
    PackageHistory newLocation = new PackageHistory();
    newLocation.setCityId(cityId);
    newLocation.setPackageId(pack.getPackageId());

    packageService.addToHistory(newLocation);
    packageHistory = packageService.getHistoryForPackage(pack.getPackageId());//update history at page refresh
  }

  public List<User> getAllUsers() {
    return userService.getAllUsers();
  }

  public String redirectToAddPackage() {
    return "addPackage";
  }

  public String redirectToAdmin() {
    return "sysUser";
  }

  public String redirectToIndex() {
    return "index";
  }

  public Package getPack() {
    return pack;
  }

  public void setPack(Package pack) {
    this.pack = pack;
  }

  public List<PackageHistory> getPackageHistory() {
    return packageHistory;
  }

  public void setPackageHistory(List<PackageHistory> packageHistory) {
    this.packageHistory = packageHistory;
  }

}

distributedSystems/java/Assignment 5/Assignment5_Client/src/java/lorenzo/pat/controller/UserController.java
package lorenzo.pat.controller;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import lorenzo.pat.model.PackageService;
import lorenzo.pat.model.UserService;
import lorenzo.pat.webservice.User;
import org.tempuri.Package;
import org.tempuri1.PackageHistory;

@ManagedBean
@RequestScoped
public class UserController {

  private PackageService packageService;
  private Package pack;
  private UserService userService;
  private User loggedUser;
  private List<PackageHistory> packageHistory;

  public UserController() {
    HttpSession session = getSession();
    loggedUser = (User) session.getAttribute("loginUser");
    pack = new Package();
    packageService = new PackageService();
    packageHistory = new ArrayList<>();
    userService = new UserService();
  }

  public String addPackage() {
    
    pack.setStatus("in deposit");
    pack.setTrackFlag(false);
    pack.setUserId(loggedUser.getUserId());
    System.out.println("from user " + pack.getTitle() + " " + pack.getPackageId());
    packageService.addPackage(pack);
    return "user";
  }
  
  public List<Package> getMyPackages() {
    return packageService.getPackagesForUser(loggedUser.getUserId());
  }

  public String getCityName(int cityId) {
    return userService.getCity(cityId).getName();

  }

  public String getHistoryForPackage(int packageId) {
    packageHistory = packageService.getHistoryForPackage(packageId);
    return "history";
  }
  
    public Package getPack() {
    return pack;
  }

  public void setPack(Package pack) {
    this.pack = pack;
  }

  public String redirectToIndex() {
    return "index";
  }

  public String redirectToUser() {
    return "user";
  }

  public List<PackageHistory> getPackageHistory() {
    return packageHistory;
  }

  public void setPackageHistory(List<PackageHistory> packageHistory) {
    this.packageHistory = packageHistory;
  }

  private HttpSession getSession() {
    FacesContext context = FacesContext.getCurrentInstance();
    HttpSession session = (HttpSession) context.getExternalContext().getSession(true);
    return session;
  }

}

distributedSystems/java/Assignment 5/Assignment5_Client/web/addPackage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
  <h:head>
    <title>Add package</title>
  </h:head>
  <h:body>

    <h:form>
      <h:outputLabel value="Title: "/>    <h:inputText value="#{userController.pack.title}"/> <br/>

      <h:commandButton value="Add package" action="#{userController.addPackage}"/>
    </h:form>

    <h:form>
      <h:commandLink value="Back" action="#{userController.redirectToUser()}"/>
    </h:form>

  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
  <h:head>
    <title>Admin page</title>
  </h:head>
  <h:body>
    
    <h:outputLabel value="Hello #{loginUser.username}!"/>
    <br/>
    <h:outputLabel value="Register new system user." />
    <h:form>
      <h:outputLabel value ="Username: "/>      <h:inputText value="#{loginController.newUser.username}"/>     <br/>
      <h:outputLabel value ="Password: "/>      <h:inputSecret value="#{loginController.newUser.password}"/>   <br/>
      <h:outputLabel value ="Full name: "/>     <h:inputText value="#{loginController.newUser.fullName}"/>     <br/>
      <h:outputLabel value ="Address: "/>       <h:inputText value="#{loginController.newUser.address}"/>      <br/>
      <h:outputLabel value ="City: "/>
      <h:selectOneMenu value="#{loginController.newUser.cityId}">
        <f:selectItems value="#{loginController.allCities}" var="city" itemLabel="#{city.name}" itemValue="#{city.cityId}" />
      </h:selectOneMenu> <br/>

      <h:commandButton action="#{loginController.registerSysUser()}" value="Register"/>
    </h:form>

    <h:form>
      <h:commandLink value="Back to login page" action="#{loginController.redirectToIndex()}"/>
    </h:form>
    
  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/history.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
  <h:head>
    <title>Facelet Title</title>
  </h:head>
  <h:body>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>City</th>
        </tr>
      </thead>

      <tbody>
        <c:forEach items="#{userController.packageHistory}" var="history">
          <tr>
            <h:form>
              <td><h:outputLabel value="#{history.hour}" /></td>
              <td><h:outputLabel value="#{userController.getCityName(history.cityId)}" /></td>
            </h:form>
          </tr>
        </c:forEach>
      </tbody>
    </table>

    <br/>
    <h:form>
      <h:commandLink value="Back" action="#{userController.redirectToUser}"/>
    </h:form>
  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
  <h:head>
    <title>Packet tracing</title>
  </h:head>
  <h:body>

    <h:form>
      <h:outputLabel value="Wellcome!" /><br/>
      <h:outputLabel value="Username: " /> <h:inputText value="#{loginController.user.username}" /><br/>
      <h:outputLabel value="Password: " /> <h:inputSecret value="#{loginController.user.password}" /><br/>

      <h:commandButton action="#{loginController.checkLogin()}" value="Log in"/>
    </h:form>
    <h:form>
      <h:commandLink action="#{loginController.redirectToRegister()}" value="Register"/>
    </h:form>

  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
  <h:head>
    <title>Register</title>
  </h:head>
  <h:body>
    <h:outputText value="Wellcome! Please register"/>

    <h:form>
      <h:outputLabel value ="Username: "/>      <h:inputText value="#{loginController.newUser.username}"/>     <br/>
      <h:outputLabel value ="Password: "/>      <h:inputSecret value="#{loginController.newUser.password}"/>   <br/>
      <h:outputLabel value ="Full name: "/>     <h:inputText value="#{loginController.newUser.fullName}"/>     <br/>
      <h:outputLabel value ="Address: "/>       <h:inputText value="#{loginController.newUser.address}"/>      <br/>
      <h:outputLabel value ="City: "/>
      <h:selectOneMenu value="#{loginController.newUser.cityId}">
        <f:selectItems value="#{loginController.allCities}" var="city" itemLabel="#{city.name}" itemValue="#{city.cityId}" />
      </h:selectOneMenu> <br/>

      <h:commandButton action="#{loginController.registerUser()}" value="Register"/>
    </h:form>

    <h:form>
      <h:commandLink value="Back to login page" action="#{loginController.redirectToIndex()}"/>
    </h:form>
  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/sysUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
  <h:head>
    <title>Sys user</title>
  </h:head>
  <h:body>
    
    <h:outputLabel value="Hello #{loginUser.username}!"/>
    

    
    <table>
      <thead>
        <tr>
          <th>PackageId</th>
          <th>Title</th>
          <th>Status</th>
          <th>UserId</th>
          <th>TrackFlag</th>
          <th colspan="3">Action</th>
        </tr>
      </thead>

      <tbody>

        <c:forEach items="#{adminController.allPackages}" var="pack">
          <tr>
            
            <h:form>
              <td><h:outputLabel value="#{pack.packageId}" /></td>
              <td><h:outputLabel value="#{pack.title}" /></td>
              <td><h:outputLabel value="#{pack.status}" /></td>
              <td><h:outputLabel value="#{pack.userId}" /></td>
              <td><h:outputLabel value="#{pack.trackFlag}" /></td>
              <td>
                <h:commandButton value="Update" action="#{adminController.prepareUpdate(pack)}"/>
              </td>
              <td>
                <h:commandButton value="Delete" action="#{adminController.removePackage(pack.packageId)}"/>
              </td>
              <td>
                <h:commandButton value="Register for tracking" action="#{adminController.registerForTracking(pack.packageId)}" disabled="#{pack.trackFlag}"/>
              </td>
            </h:form>
       
            
          </tr>
        </c:forEach>
      </tbody>
    </table>
    
    <br/>
    <h:form>
      <h:commandLink value="Log out" action="#{adminController.redirectToIndex}"/>
    </h:form>
    
  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/update.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
  <h:head>
    <title>Update page</title>
  </h:head>
  <h:body>

    <h:outputLabel value="Package id: #{adminController.pack.packageId}" /> <br/>

    <h:form> 
      <h:outputLabel value="Package status: " />
      <h:selectOneMenu value="#{status}">
        <f:selectItem itemValue="in deposit" itemLabel="in deposit" />
        <f:selectItem itemValue="on route" itemLabel="on route" />
        <f:selectItem itemValue="delivered" itemLabel="delivered" />
      </h:selectOneMenu> <br/>

      <h:commandButton value="Update package status" action="#{adminController.updatePackageStatus(status)}"/>
    </h:form>

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>City</th>
        </tr>
      </thead>

      <tbody>
        <c:forEach items="#{adminController.packageHistory}" var="history">
          <tr>
            <h:form>
              <td><h:outputLabel value="#{history.hour}" /></td>
              <td><h:outputLabel value="#{adminController.getCityName(history.cityId)}" /></td>
            </h:form>
          </tr>
        </c:forEach>
      </tbody>
    </table>

    <h:form>
      <h:outputLabel value="City" />
      <h:selectOneMenu value="#{newCityId}">
        <f:selectItems value="#{adminController.allCities}" var="city" itemLabel="#{city.name}" itemValue="#{city.cityId}" />
      </h:selectOneMenu> <br/>

      <h:commandButton action="#{adminController.addToHistory(newCityId)}" value="Add location"/>
    </h:form>

    <h:form>
      <h:commandLink value="Back" action="#{adminController.redirectToAdmin}"/>
    </h:form>

  </h:body>
</html>

distributedSystems/java/Assignment 5/Assignment5_Client/web/user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
  <h:head>
    <title>User page</title>
  </h:head>
  <h:body>

    <h:outputLabel value="Hello #{loginUser.username}!"/>

        <h:form>
      <h:commandLink value="Add package" action="#{adminController.redirectToAddPackage}"/>
    </h:form>
    
    <table>
      <thead>
        <tr>
          <th>PackageId</th>
          <th>Title</th>
          <th>Status</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <c:forEach items="#{userController.myPackages}" var="pack">
          <tr>
            <h:form>
              <td><h:outputLabel value="#{pack.packageId}" /></td>
              <td><h:outputLabel value="#{pack.title}" /></td>
              <td><h:outputLabel value="#{pack.status}" /></td>
              <td>
                <h:commandButton value="Show history" action="#{userController.getHistoryForPackage(pack.packageId)}" />
              </td>
            </h:form>
          </tr>
        </c:forEach>
      </tbody>
    </table>

    <br/>
    <h:form>
      <h:commandLink value="Log out" action="#{userController.redirectToIndex}"/>
    </h:form>

  </h:body>
</html>